id: I992DD3B0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T17:37:54+00:00'
last_modified: '2022-06-10T04:10:35.033211+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3708
  title: མཁྱུད་སྤྱད་སྣ་ཚོགས་ཕྱོགས་བསྡུས་ཙིནྟ་མ་ཎི་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F6B1:
      image_group_id: I1KG3748
      title: Volume 1 of mkhyud spyad sna tshogs phyogs bsdus tsin+ta ma Ni
      total_pages: 236
      order: 1
      base_file: F6B1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
