id: P000327
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3708
  title: མཁྱུད་སྤྱད་སྣ་ཚོགས་ཕྱོགས་བསྡུས་ཙིནྟ་མ་ཎི་
  author: ''
  volumes:
    67b4a93a5a4c4b3fad12fac08f556d0e:
      image_group_id: I1KG3748
      title: Volume 1 of mkhyud spyad sna tshogs phyogs bsdus tsin+ta ma Ni
      volume_number: 1
      total_pages: 236
      base_file: v001.txt
ebook_metadata:
  title: མཁྱུད་སྤྱད་སྣ་ཚོགས་ཕྱོགས་བསྡུས་ཙིནྟ་མ་ཎི་
  author: ''
  sku: P000327
  cover: cover.jpg
  layers:
  - pagination
